work_group: ${TEAM:amd}
user_name: ${USER:root}
exp_name: ${EXP_NAME:llama3_70B-pretrain}
workspace: ./output

modules:
  pre_trainer:
    framework: torchtitan
    config: pre_trainer.yaml

    # model to run
    model: llama3.1_70B_fp8-converter.yaml
    overrides:
      sink_level: null
      file_sink_level: DEBUG
      stderr_sink_level: INFO

      lr_scheduler:
        # lr scheduler warm up
        warmup_steps: 10

      metrics:
        log_freq: 1

      training:
        batch_size: 3
        compile: true
        steps: 50

      optimizer:
        lr: 1.5e-4

      activation_checkpoint:
        mode: full

      float8:
        enable_fsdp_float8_all_gather: true
        precompute_float8_dynamic_scale_for_fsdp: true
        force_recompute_fp8_weight_in_bwd: true
        filter_fqns: ["output"]

      primus_turbo:
        enable_primus_turbo : true
        enable_attention_float8 : false
